version: "3.8"

services:
  briteshub:
    image: l32oo/briteshub:v3
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.briteshub.rule=Host(`briteshub.com.br`)"
        - "traefik.http.routers.briteshub.entrypoints=websecure"
        - "traefik.http.routers.briteshub.tls.certresolver=letsencrypt"
        - "traefik.http.services.briteshub.loadbalancer.server.port=80"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true