version: "3.8"

services:
  briteshub_site:
    build: .
    container_name: briteshub_site
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.briteshub.rule=Host(`briteshub.com.br`)"
      - "traefik.http.routers.briteshub.entrypoints=websecure"
      - "traefik.http.routers.briteshub.tls=true"
      - "traefik.http.services.briteshub.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
